a = input("Adad aval ra vared konid:")
b = input("Adad dovom ra vared konid:")
a = int(a)
b = int(b)
print ("a+b=",a+b)
print ("a-b=",a-b)
print ("a/b=",a/b)
print ("a*b=",a*b)
print ("@@@@@@@@")
print (20+12-14/2)
print ("@@@@@@@@")
print (20>18)
print (20<18)
print (20>=20)
print (20==17)